---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrk-jenkins-preto-01
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: wrk-jenkins-preto-01
  template:
    metadata:
      labels:
        app: wrk-jenkins-preto-01
    spec:
      containers:
        - name: wrk-jenkins-preto-01
          image: chrismarsilva/cms-python-jenkins:{{tag}}
          #image: chrismarsilva/cms-python-jenkins:6
          ports:
            - containerPort: 8082
          imagePullPolicy: Never
          env:
          - name: COR
            value: PRETO-01
---
apiVersion: v1
kind: Service
metadata:
  name: wrk-jenkins-preto-01
spec:
  selector:
    app: wrk-jenkins-preto-01
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8082
  type: LoadBalancer
---