version: "3.8"

networks:
  network-web-fastapi-proxy:
    driver: bridge

services:

  wrk-jenkins-nginx:
    container_name: wrk-jenkins-nginx
    image: nginx:1.21.6-alpine
    restart: always
    volumes:
      - ./api_secret.jwk:/etc/nginx/api_secret.jwk
      - ./nginx.conf:/etc/nginx/nginx.conf  # para Configurações Gerais
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf  # para Configurações Específicas  # comente enviar os "upstream" e o "server", nao deve ter o "events" e nem o "http"
      - ./log/nginx:/var/log/nginx
      #- static:/static
    ports:
      - 80:80
    depends_on:
      - wrk-fastapi-jenkins-01
      - wrk-fastapi-jenkins-02
    networks:
      - network-web-fastapi-proxy

  wrk-jenkins-preto-01:
    container_name: wrk-jenkins-preto-01
    build: .
    restart: always
    environment:
      - COR=000000
      - COR_DESCR=PRETO
    volumes:
      - ./main.py:/usr/app/main.py
      #- .:/code
      #- static:/static
    networks:
      - network-web-fastapi-proxy

  wrk-jenkins-preto-02:
    container_name: wrk-jenkins-preto-02
    build: .
    restart: always
    environment:
      - COR=FF0000
      - COR_DESCR=VERMELHO
    volumes:
      - ./main.py:/usr/app/main.py
    networks:
      - network-web-fastapi-proxy

  wrk-jenkins-verde-01:
    container_name: wrk-jenkins-verde-01
    build: .
    restart: always
    environment:
      - COR=00FF00
      - COR_DESCR=VERDE
    volumes:
      - ./main.py:/usr/app/main.py
    networks:
      - network-web-fastapi-proxy

  wrk-jenkins-verde-02:
    container_name: wrk-jenkins-verde-02
    build: .
    restart: always
    environment:
      - COR=0000FF
      - COR_DESCR=AZUL
    volumes:
      - ./main.py:/usr/app/main.py
    networks:
      - network-web-fastapi-proxy
